-- SQLite


CREATE TABLE Events (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Title TEXT NOT NULL,
Description TEXT,
Location TEXT,
Start_time TEXT NOT NULL,
End_time TEXT NOT NULL,
Organizer_id INTEGER NOT NULL,
Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FakeId INTEGER NOT NULL,
FOREIGN KEY (Organizer_id) REFERENCES Professionals(Id)
);


//make FakeId NULL



delete from Events

drop table Events



CREATE TABLE Participants (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Name TEXT NOT NULL,
Email TEXT NOT NULL,
Event_id INTEGER NOT NULL,
Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FakeId INTEGER NOT NULL,
FOREIGN KEY (Event_id) REFERENCES Events(Id)
);

CREATE TABLE Availability (
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Start_time TEXT NOT NULL,
End_time TEXT NOT NULL,
User_id INTEGER NOT NULL,
Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FakeId INTEGER NOT NULL,
FOREIGN KEY (User_id) REFERENCES Professionals(Id)
);


